### PR TITLE
Core rust

### PR DESCRIPTION
**Pull request by Chronal**
## Context

Porting core to rust

## Changes

This PR introduces the following changes:
* Adds the `core_rust` folder

## Tasks

I've completed the following tasks:
- [x] Signed the Contributers License Agreement (CLA)
- [ ] Added/updated tests
- [ ] Added/updated docs

### CODE REVIEW

**Comment by Chronal** [comment]
Had to do a rebase to fix the author for some of the commits, see if you can merge it now @cjoy

**Comment by cjoy** [comment]
@Chronal can we get core_rust in a usable state before merging to master? Would it be okay if we kept this PR up and incrementally added to it.

**Comment by Chronal** [comment]
Sure, sounds good.

**Comment by cjoy** [comment]
Closing this PR, we can re-open if/when we start re-writing to rust.

**Pull request closed without merging**
